Unittesting/setup
joha4270/electric-mouse pull request #36
Opened 2016-12-11 15:15 UTC by nbreum15

2016-12-11 17:44 UTC, jakobbsm requested changes

2016-12-11 17:44 UTC, jakobbsm commented on src/electric-mouse/Services/SectionService.cs
> +            RouteSection section = new RouteSection { Name = name, RouteHall = _dbContext.RouteHalls.First(h => h.RouteHallID == routeHallId) };
Line is too long, you should also split up your query. To make it even cleaner making a separate variable for routehall might be viable.

2016-12-11 17:44 UTC, jakobbsm commented on src/electric-mouse/Services/SectionService.cs
> +        public List<RouteSection> GetAllRouteSections()
Not sure about the readability on this one. Might be easier if it had a normal wrapper.

2016-12-11 17:44 UTC, jakobbsm commented on src/electric-mouse/Services/SectionService.cs
> +            List<RouteSectionRelation> relations = _dbContext.RouteSectionRelations.Include(rs => rs.Route)
New line

2016-12-11 17:44 UTC, jakobbsm commented on test/FileExtensionsTest.cs
> +        public void HasExtension_CheckForPNGInFileNameWithPNG_ReturnsTrue()
Shouldn't the class name make the suffix unnecessary?

2016-12-11 17:44 UTC, jakobbsm commented on test/project.json
> +    "moq.netcore": "4.4.0-beta8",
Replace with: `"Moq": "4.6.38-alpha",`

2016-12-12 07:59 UTC, nbreum15 commented
fuck u, not gonna happen bitch.

2016-12-12 08:00 UTC, jakobbsm commented
Not fixing will lead to closes.

2016-12-12 08:13 UTC, merged

2016-12-12 08:13 UTC, jakobbsm commented
We need it for master branch, so I'll let the changes pass for now. Look into them later though.